kafka:
  brokers:
    - dialogue-service-kafka1:29091
    - dialogue-service-kafka2:29092
    - dialogue-service-kafka3:29093
  producers:
    counter_commands:
      topic: "counter_commands"
  consumers:
    dialogue_commands:
      topic: "dialogue_commands"

database:
  host: "dialogue-service-master"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: ""
