service:
  grpc_port: 38084

kafka:
  brokers:
    - localhost:9091
    - localhost:9092
    - localhost:9093
  producers:
    dialogue_commands:
      topic: "dialogue_commands"
  consumers:
    counter_commands:
      topic: "counter_commands"

database:
  host: "localhost"
  port: 35432
  dbname: "postgres"
  user: "postgres"
  password: "123"
